sudo: false
language: node_js
node_js:
  - '8'
before_install: npm update
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm run build
script:
  - npm run coverage
after_success:
  - npm run report-coverage
