language: node_js
node_js:
  - '8'
before_install: if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm run build
script: npm run test
